# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paq', models.CharField(help_text='Introduce el c\xf3digo del paquete', max_length=5, unique=True, verbose_name='C\xf3digo de paquete')),
                ('nom_paq', models.CharField(help_text='Introduce el nombre del paquete', max_length=100, verbose_name='Nombre del paquete')),
                ('des_paq', models.TextField(help_text='Introduzca la descripci\xf3n del paquete', max_length=255, verbose_name='Descripci\xf3n del paquete')),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
            },
        ),
    ]
