# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 21:05
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=250)),
                ('nombre_fiscal', models.CharField(max_length=250)),
                ('tipo_via', models.CharField(max_length=5)),
                ('direccion1', models.CharField(max_length=250)),
                ('direccion2', models.CharField(blank=True, max_length=250, null=True)),
                ('direccion3', models.CharField(blank=True, max_length=250, null=True)),
                ('numero', models.CharField(max_length=15)),
                ('poblacion', models.CharField(max_length=250)),
                ('cod_pos', models.CharField(max_length=6)),
                ('provincia', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('registro', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpUsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cod', models.CharField(max_length=5)),
                ('usu_cod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mor_empcod', models.CharField(max_length=20)),
                ('mor_modcod', models.CharField(max_length=20)),
                ('mor_rolcod', models.CharField(max_length=20)),
                ('mor_insercion', models.CharField(max_length=1)),
                ('mor_borrado', models.CharField(max_length=1)),
                ('mor_modificacion', models.CharField(max_length=1)),
                ('mor_consulta', models.CharField(max_length=1)),
                ('mor_exportacion', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_apl', models.CharField(max_length=5)),
                ('mod_codigo', models.CharField(max_length=20)),
                ('mod_desc', models.CharField(max_length=250)),
                ('mod_version', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cod', models.CharField(max_length=5)),
                ('rol_cod', models.CharField(max_length=20)),
                ('rol_desc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rou_empcod', models.CharField(max_length=20)),
                ('rou_rolcod', models.CharField(max_length=20)),
                ('rou_usucod', models.CharField(max_length=20)),
                ('rou_activo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_cod', models.CharField(max_length=20)),
                ('usu_nom', models.CharField(max_length=50)),
                ('usu_idi', models.CharField(max_length=20)),
                ('usu_email', models.CharField(max_length=250)),
                ('usu_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
