# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=250)),
                ('nombre_fiscal', models.CharField(max_length=250)),
                ('tipo_via', models.CharField(max_length=5)),
                ('direccion1', models.CharField(max_length=250)),
                ('direccion2', models.CharField(max_length=250)),
                ('direccion3', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=15)),
                ('poblacion', models.CharField(max_length=250)),
                ('cp', models.CharField(max_length=6)),
                ('provincia', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('movil', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
                ('regsitro', models.CharField(max_length=250)),
            ],
        ),
    ]
