# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=250)),
                ('nombre_fiscal', models.CharField(max_length=250)),
                ('tipo_via', models.CharField(max_length=5)),
                ('direccion1', models.CharField(max_length=250)),
                ('direccion2', models.CharField(blank=True, max_length=250, null=True)),
                ('direccion3', models.CharField(blank=True, max_length=250, null=True)),
                ('numero', models.CharField(max_length=15)),
                ('poblacion', models.CharField(max_length=250)),
                ('cod_pos', models.CharField(max_length=6)),
                ('provincia', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('registro', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpUsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cod', models.CharField(max_length=5)),
                ('usu_cod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mor_empcod', models.CharField(max_length=20)),
                ('mor_modcod', models.CharField(max_length=20)),
                ('mor_rolcod', models.CharField(max_length=20)),
                ('mor_insercion', models.CharField(max_length=1)),
                ('mor_borrado', models.CharField(max_length=1)),
                ('mor_modificacion', models.CharField(max_length=1)),
                ('mor_consulta', models.CharField(max_length=1)),
                ('mor_exportacion', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_apl', models.CharField(max_length=5)),
                ('mod_codigo', models.CharField(max_length=20)),
                ('mod_desc', models.CharField(max_length=250)),
                ('mod_version', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cod', models.CharField(max_length=5)),
                ('rol_cod', models.CharField(max_length=20)),
                ('rol_desc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rou_empcod', models.CharField(max_length=20)),
                ('rou_rolcod', models.CharField(max_length=20)),
                ('rou_usucod', models.CharField(max_length=20)),
                ('rou_activo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_cod', models.CharField(max_length=20)),
                ('usu_nom', models.CharField(max_length=50)),
                ('usu_idi', models.CharField(max_length=20)),
                ('usu_email', models.CharField(max_length=250)),
                ('usu_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
